# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.2
  - 1.3
  - 1.4
  - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg, Strategems; Pkg.add("Coverage"); using Coverage; cd(joinpath(dirname(pathof(Strategems)), "..")); Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg, Strategems; Pkg.add("Coverage"); using Coverage; cd(joinpath(dirname(pathof(Strategems)), "..")); Codecov.submit(Codecov.process_folder())'

